apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
      - name: simple-webapp
        image: <your-image-registry>/simple-webapp:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: webapp-config
        - secretRef:
            name: webapp-secret
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
spec:
  selector:
    app: simple-webapp
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: simple-webapp
spec:
  to:
    kind: Service
    name: simple-webapp

